AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot 2 API - br.com.vitxr.smartpersonal::smartpersonal
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  SmartPersonalFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: br.com.vitxr.smartpersonal.StreamLambdaHandler::handleRequest
      Runtime: java21
      CodeUri: .
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 30
      Events:
        ProxyResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  SmartPersonalApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/prod/'
    Export:
      Name: SmartPersonalApi
