package br.com.vitxr.smartpersonal.entity;

import br.com.vitxr.smartpersonal.utils.LocalDateConverter;
import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDate;

@AllArgsConstructor
@NoArgsConstructor
@Getter
@Setter
@DynamoDBTable(tableName = "UsersTB")
public class User {

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String name;

    @DynamoDBAttribute
    private String email;

    @DynamoDBAttribute
    private String password;

//    @DynamoDBAttribute
//    @DynamoDBTypeConverted(converter = LocalDateConverter.class)  // Conversão adicionada aqui
//    private LocalDate birthday;
//
//    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.N)
//    private double height;
//
//    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.N)
//    private double weight;
//
//    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.BOOL)
//    private boolean active;

}
