package br.com.vitxr.smartpersonal.entity;

import br.com.vitxr.smartpersonal.utils.LocalDateConverter;
import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDate;

@AllArgsConstructor
@NoArgsConstructor
@Getter
@Setter
@DynamoDBTable(tableName = "UsersTB")
public class User {

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String name;

    @DynamoDBAttribute
    private String email;

    @DynamoDBAttribute
    private String password;

    @DynamoDBAttribute
    private String birthday; // formato ISO-8601 recomendado, ex: "1999-08-15"

    @DynamoDBAttribute
    private Double height;

    @DynamoDBAttribute
    private Double weight;

    @DynamoDBAttribute
    private Boolean active;

}
